package group8_java.school_business_tour_management.views;

import group8_java.school_business_tour_management.common.MessageDialog;
import group8_java.school_business_tour_management.models.Teacher;
import group8_java.school_business_tour_management.models.Tour;
import group8_java.school_business_tour_management.services.TeacherService;
import group8_java.school_business_tour_management.services.TourService;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pham Vu
 */
public class ManageToursOfCompany extends javax.swing.JFrame {

    private int companyId;
    
    public void setCompanyId(int comId) {
        this.companyId = comId; 
    }
    
    public int getCompanyId() {
        return companyId;
    }
    /**
     * Creates new form ManageBusssiness
     */
    public ManageToursOfCompany() {
        initComponents();
        setLocationRelativeTo(null);
        System.out.println("CompanyID: " +  getCompanyId());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        toursOfCompanyTable = new javax.swing.JTable();
        companyNameLabel = new javax.swing.JLabel();
        companyEmailLabel = new javax.swing.JLabel();
        companyPhoneLabel = new javax.swing.JLabel();
        companyAddressLabel = new javax.swing.JLabel();
        companyDescriptionLabel = new javax.swing.JLabel();
        createCompanyButton = new javax.swing.JButton();
        companyCodeLabel = new javax.swing.JLabel();
        returnBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Danh sách các chuyến tham quan do một doanh nghiệp tổ chức");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Các chuyến tham quan doanh nghiệp công ty tổ chức");

        toursOfCompanyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        toursOfCompanyTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toursOfCompanyTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(toursOfCompanyTable);

        companyNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        companyNameLabel.setText("Tên doanh nghiệp: ");

        companyEmailLabel.setText("Email: ");

        companyPhoneLabel.setText("Điện thoại: ");

        companyAddressLabel.setText("Địa chỉ: ");

        companyDescriptionLabel.setText("Ghi chú: ");

        createCompanyButton.setText("Quản lí các chuyến tham quan");
        createCompanyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCompanyActionPerformed(evt);
            }
        });

        companyCodeLabel.setText("Mã doanh nghiệp: ");

        returnBackButton.setText("Quay lại trang trước");
        returnBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(companyPhoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(companyAddressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(companyCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(companyNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(companyEmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(companyDescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(createCompanyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(returnBackButton)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(28, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(returnBackButton)
                .addGap(5, 5, 5)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(companyCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(companyNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(companyPhoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(companyEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(companyAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(companyDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createCompanyButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearAllFields() {

    } 

    private DefaultTableModel tableModel;

    private void loadTableData() {
        try {
            List<Tour> data = TourService.getAllToursByCompanyId(companyId);
            List<Teacher> teacher_data = TeacherService.getAllTeachers();
            tableModel.setRowCount(0);            
            if (data != null) {
                for (Tour tour : data) {
                    String teacherName = "";
                    for (Teacher tea : teacher_data) {
                        if(tea.getId() == tour.getTeacherId()) {
                            teacherName =  tea.getLastName()  + " " + tea.getFirstName();
                        }
                    }
                    tableModel.addRow(new Object[]{tour.getCode(), tour.getName(),
                        tour.getStartDate(),tour.getDescription(),
                        tour.getAvailables(),tour.getPresentator(),teacherName});
                    
                }
            }
            tableModel.fireTableDataChanged();
        } catch (Exception ex) {
            MessageDialog.showErrorDialog(this, "Tải dữ liệu cho bảng có lỗi! Chi tiết: " + ex.getMessage(), "Có lỗi xảy ra");
            ex.printStackTrace();
        }
    }

    public void initializeTable() {
        tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(new String[]{"Mã chuyến", "Tên chuyến",
            "Ngày khởi hành", "Mô tả", "Số ghế","Người thuyết trình","Giáo viên"});
        toursOfCompanyTable.setModel(tableModel);

        loadTableData();
    }


    private void createCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCompanyActionPerformed
        try {
            ManageTour tourscreen = new ManageTour();
            tourscreen.setVisible(true);
            dispose();
        } catch (Exception ex) {
            MessageDialog.showErrorDialog(this, "Phát hiện lỗi khi thêm doanh nghiệp, chi tiết: " + ex.getMessage() + "\n" + ex.toString() + "\n", "Có lỗi xảy ra");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_createCompanyActionPerformed

    private void toursOfCompanyTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toursOfCompanyTableMouseClicked
        try {
            int index = toursOfCompanyTable.getSelectedRow();
            if (index == -1) {
                MessageDialog.showInfoDialog(this, "Vui chọn chọn doanh nghiệp", "Thông báo");
                return;
            }

        } catch (Exception ex) {
            MessageDialog.showErrorDialog(this, "Có lỗi, chi tiết: " + ex.getMessage() + "\n" + ex.toString() + "\n", "Phát hiện lỗi");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_toursOfCompanyTableMouseClicked

    private void returnBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBackButtonActionPerformed
        ManageCompany mcScreen = new ManageCompany();
        mcScreen.setVisible(true);
        dispose();
    }//GEN-LAST:event_returnBackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageToursOfCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageToursOfCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageToursOfCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageToursOfCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageToursOfCompany().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel companyAddressLabel;
    private javax.swing.JLabel companyCodeLabel;
    private javax.swing.JLabel companyDescriptionLabel;
    private javax.swing.JLabel companyEmailLabel;
    private javax.swing.JLabel companyNameLabel;
    private javax.swing.JLabel companyPhoneLabel;
    private javax.swing.JButton createCompanyButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton returnBackButton;
    private javax.swing.JTable toursOfCompanyTable;
    // End of variables declaration//GEN-END:variables

    public JLabel getCompanyAddressLabel() {
        return companyAddressLabel;
    }

    public void setCompanyAddressLabel(JLabel companyAddressLabel) {
        this.companyAddressLabel = companyAddressLabel;
    }

    public JLabel getCompanyCodeLabel() {
        return companyCodeLabel;
    }

    public void setCompanyCodeLabel(JLabel companyCodeLabel) {
        this.companyCodeLabel = companyCodeLabel;
    }

    public JLabel getCompanyDescriptionLabel() {
        return companyDescriptionLabel;
    }

    public void setCompanyDescriptionLabel(JLabel companyDescriptionLabel) {
        this.companyDescriptionLabel = companyDescriptionLabel;
    }

    public JLabel getCompanyEmailLabel() {
        return companyEmailLabel;
    }

    public void setCompanyEmailLabel(JLabel companyEmailLabel) {
        this.companyEmailLabel = companyEmailLabel;
    }

    public JLabel getCompanyNameLabel() {
        return companyNameLabel;
    }

    public void setCompanyNameLabel(JLabel companyNameLabel) {
        this.companyNameLabel = companyNameLabel;
    }

    public JLabel getCompanyPhoneLabel() {
        return companyPhoneLabel;
    }
    

    public void setCompanyPhoneLabel(JLabel companyPhoneLabel) {
        this.companyPhoneLabel = companyPhoneLabel;
    }

}
